### ISSUE TITLE
Doesn't work for "non-traditional" subjects i.e. LSAT

### ISSUE THREAD

**Issue by syndacks** [rand-net/khan-dl#2]
Hello, I tried this for the LSAT (multiple iterations of URLs, but it seems the scraper hasn't been setup to handle this).

At some point I'd like to open a PR for this but figured I'd let you know in the meantime. 

stacktrace:
```
https://www.khanacademy.org/test-prep/lsat

Looking up https://www.khanacademy.org/test-prep/lsat .....
Generating Path Slugs..... 
Traceback (most recent call last):
  File "./khan-dl.py", line 40, in <module>
    khan_down.generate_unit_slugs()
  File "/~/repos/khan-dl/khan_downloader.py", line 25, in generate_unit_slugs
    course_title = self.course_root_page_html.find(
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by rand-net** [comment]
It currently doesn't support non-traditional subjects.

**Comment by syndacks** [comment]
Cool, you're welcome.
