### ISSUE TITLE
 HTTP Error 410: API removed

### ISSUE THREAD

**Issue by jacobm3** [rand-net/khan-dl#20]
I'm unable to download the algebra course with a fresh install of khan-dl through pip. 

 ```
ubuntu@optiplex9020:/mnt/g/khan-dl-downloads         2022-03-13 13:52:36
$ khan-dl -c https://www.khanacademy.org/math/algebra
 _  __ _   _     _     _   _         ____   _
| |/ /| | | |   / \   | \ | |       |  _ \ | |
| ' / | |_| |  / _ \  |  \| | _____ | | | || |
| . \ |  _  | / ___ \ | |\  ||_____|| |_| || |___
|_|\_\|_| |_|/_/   \_\|_| \_|       |____/ |_____|


Looking up https://www.khanacademy.org/math/algebra...
Course URL: https://www.khanacademy.org/math/algebra

Generating Path Slugs...

Collecting Youtube IDs:   0.0% [>                                                                                                        ]   0/ 15 eta [?:??:??]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: API removed. Please see https://github.com/Khan/khan-api for details.

ubuntu@optiplex9020:/mnt/g/khan-dl-downloads         2022-03-13 13:52:39
$ pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
ubuntu@optiplex9020:/mnt/g/khan-dl-downloads         2022-03-13 13:52:43
$ pip list | egrep 'khan|youtube'
khan-dl                1.2.1
youtube-dl             2020.3.24

```

**Comment by jacobm3** [comment]
I installed the latest khan-dl and youtube-dl from the repos with `sudo python3 setup.py install` and saw a different error. Attaching the debug log here.

Snippet:

```
$ khan-dl -c https://www.khanacademy.org/math/algebra -v 3 2>&1 | tee log.txt

<cut>

Looking up https://www.khanacademy.org/math/algebra...
Course URL: https://www.khanacademy.org/math/algebra

Generating Path Slugs...

DEBUG:root:Collection youtube ids for unit:htt
[log.txt](https://github.com/rand-net/khan-dl/files/8240498/log.txt)
ps://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:foundation-algebra
DEBUG:root:Collection youtube ids for unit:https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:foundation-algebra
Collecting Youtube IDs:   0.0% [>                       ]   0/ 15 eta [?:??:??]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl-2021.12.17-py3.8.egg/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl-2021.12.17-py3.8.egg/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by jacobm3** [comment]
[log.txt](https://github.com/rand-net/khan-dl/files/8240499/log.txt)

**Comment by rand-net** [comment]
It seems to be an issue with the youtube-dl extractor for khanacademy. I will try to debug the issue with the extractor.

**Comment by rand-net** [comment]
Fixed in the new release. See [installation](https://github.com/rand-net/khan-dl#installation)
