### ISSUE TITLE
Cannot download Physics library: Unsupported URL

### ISSUE THREAD

**Issue by DrBanana419** [rand-net/khan-dl#22]
I installed khan-dl in the archlinux docker image, if that helps. When I try to download the physics library, it can collect 19/20 youtube IDs but fails at the last one. Here is the error:
```
Domain: Science
Selected Domain: science

Downloading Courses...

Course: Physics library
Selected Course: Physics library
Course URL: https://www.khanacademy.org/science/physics

Generating Path Slugs...

Collecting Youtube IDs:  95.0% [================================================>   ]  19/ 20 eta [00:00]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4031, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.khanacademy.org/science/cosmology-and-astronomy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/khan_dl/khan_dl.py", line 334, in get_course_youtube_ids
    info_dict = ydl.extract_info(unit_url, download=False)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1386, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1413, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 936, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 879, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Unsupported URL: https://www.khanacademy.org/science/cosmology-and-astronomy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4031, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.khanacademy.org/science/cosmology-and-astronomy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/khan-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/khan_dl/__init__.py", line 57, in main
    khan_down.download_course_interactive()
  File "/usr/lib/python3.10/site-packages/khan_dl/khan_dl.py", line 417, in download_course_interactive
    self.get_course_youtube_ids()
  File "/usr/lib/python3.10/site-packages/khan_dl/khan_dl.py", line 343, in get_course_youtube_ids
    info_dict = ydl.extract_info(
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1386, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1413, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 936, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 879, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Unsupported URL: https://www.khanacademy.org/science/cosmology-and-astronomy
```

**Comment by rand-net** [comment]
Fixed in latest release 1.2.8
