### ISSUE TITLE
Error in Reading Course Title

### ISSUE THREAD

**Issue by expert101** [rand-net/khan-dl#25]
(.venv) xxx@Vs-MacBook-Air khan % khan-dl -c "https://www.khanacademy.org/test-prep/sat-reading-and-writing"
```
 _  __ _   _     _     _   _         ____   _     
| |/ /| | | |   / \   | \ | |       |  _ \ | |    
| ' / | |_| |  / _ \  |  \| | _____ | | | || |    
| . \ |  _  | / ___ \ | |\  ||_____|| |_| || |___ 
|_|\_\|_| |_|/_/   \_\|_| \_|       |____/ |_____|
```

Looking up https://www.khanacademy.org/test-prep/sat-reading-and-writing...
Course URL: https://www.khanacademy.org/test-prep/sat-reading-and-writing

```
Traceback (most recent call last):
  File "/Users/Shared/Workspace/khan/.venv/bin/khan-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/Shared/Workspace/khan/.venv/lib/python3.12/site-packages/khan_dl/__init__.py", line 65, in main
    khan_down.download_course_given(selected_course_url)
  File "/Users/Shared/Workspace/khan/.venv/lib/python3.12/site-packages/khan_dl/khan_dl.py", line 464, in download_course_given
    self.get_course_title()
  File "/Users/Shared/Workspace/khan/.venv/lib/python3.12/site-packages/khan_dl/khan_dl.py", line 195, in get_course_title
    self.course_title = course_title.text.replace(" ", "_")
                        ^^^^^^^^^^^^^^^^^
```
**AttributeError: 'NoneType' object has no attribute 'text'**

**Comment by rand-net** [comment]
I've updated the scraper.
